# Generated by Django 4.2.6 on 2023-10-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etude', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=20)),
                ('categorie', models.CharField(max_length=20)),
                ('nombre_page', models.IntegerField()),
                ('auteur', models.CharField(max_length=15)),
            ],
        ),
    ]
